# docker-compose.yml
version: "3"
 
services:
  main:
    build: .
    container_name: tiramisu_cake
    volumes:
      - "./src:/var/www/html"
    ports:
      - "916:80"
    restart: always
    command: >
      bash -c "
      chown -R www-data:www-data /var/www/html &&
      chmod -R 755 /var/www/html &&
      /usr/sbin/apache2ctl -D FOREGROUND"